FROM python:3.11-slim-bookworm
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY provisioning_api ./provisioning_api
COPY worker ./worker
CMD ["python", "-m", "worker.main"]
